# sur quel port le serveur d√©marre
server:
  port: 8081

# Les informations de connexion de la bd
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: create